### ISSUE TITLE
Add testing to repo

### ISSUE THREAD

**Issue by idea404** [near-examples/indexer-tx-watcher-example-lake#1]
Hello! 

A month ago or so I added a mail-cron to near-examples that checks the test results for all repos there. This in order to make sure examples still work when dependencies are upgraded by dependabot.

As such the aim is for repos to have some testing in place.

**My question for you**
Could you please add some tests to: https://github.com/near-examples/indexer-tx-watcher-example-lake? This helps make sure the code in the repo keeps working through time, and also sets a good example for visitors on how they should test their code :) 

Here's an example GitHub Actions "test.yaml" file from another repo with testing (from project root /.github/workflows/test.yaml): 

```yaml
name: CI
on: 
  repository_dispatch:
    types: [tests-report]
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-2020-10-08
          target: wasm32-unknown-unknown

      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Check that build works
        run: ./build.sh
        # TODO: check that files in `res` are unchanged

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
```

The `repository_dispatch` key-value pair allows for the cron to remotely trigger the tests in this repo.
